volumes:
  static:
  pg_data:

services:
  db:
    container_name: tracker-db
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: tracker-back
    image: ${BACKEND_IMAGE}
    env_file: .env
    volumes:
      - static:/app/web
    depends_on:
      - db
    command: sh -c "sleep 5 && ./up.sh"
    restart: always

  nginx:
    container_name: tracker-gateway
    image: ${GATEWAY_IMAGE}
    env_file: .env
    volumes:
      - static:/web
    ports:
      - 8000:80
    restart: always