# Generated by Django 4.2.4 on 2023-12-05 11:07

import apps.dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "day",
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                apps.dashboard.models.get_current_date
                            )
                        ],
                        verbose_name="Day",
                    ),
                ),
                ("start", models.TimeField(verbose_name="Start Time")),
                (
                    "stop",
                    models.TimeField(blank=True, null=True, verbose_name="Stop Time"),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Duration"
                    ),
                ),
            ],
            options={
                "verbose_name": "Time",
                "verbose_name_plural": "Time",
                "ordering": ("day",),
            },
        ),
    ]
