# Generated by Django 4.2.4 on 2023-12-05 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Project Name")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Done", "Done")],
                        default="Active",
                        max_length=150,
                        verbose_name="Status",
                    ),
                ),
                ("billing", models.BooleanField(default=False, verbose_name="Billing")),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Amount"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("Hour", "per hour"), ("Month", "per month")],
                        default="Hour",
                        max_length=150,
                        verbose_name="Payment type",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="client.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("name",),
            },
        ),
    ]
